const pool = require('../config/database');
const requestFields = `rr.id, rr.user_id, rr.resource_type, rr.resource_id, rr.requested_date, rr.start_time, rr.end_time, rr.purpose, rr.research_project, rr.additional_requirements, rr.status, rr.created_at, rr.updated_at, u.name AS requester_name, u.email AS requester_email, d.code AS department_code`;
function canSee(req, row) { return req.user.role === 'admin' || req.user.role === 'faculty' || row.user_id === req.user.id; }
async function list(req, res) { const values = []; let where = ''; if (req.user.role === 'student') { values.push(req.user.id); where = 'WHERE rr.user_id = $1'; } else if (req.user.role === 'faculty') { values.push(req.user.departmentId); where = 'WHERE d.id = $1'; } const result = await pool.query(`SELECT ${requestFields} FROM resource_requests rr JOIN users u ON u.id = rr.user_id LEFT JOIN departments d ON d.id = u.department_id ${where} ORDER BY rr.created_at DESC`, values); res.json({ success: true, data: result.rows }); }
async function get(req, res) { const result = await pool.query(`SELECT ${requestFields} FROM resource_requests rr JOIN users u ON u.id = rr.user_id LEFT JOIN departments d ON d.id = u.department_id WHERE rr.id = $1`, [req.params.id]); if (!result.rowCount) return res.status(404).json({ success: false, message: 'Request not found' }); if (!canSee(req, result.rows[0])) return res.status(403).json({ success: false, message: 'You cannot view this request' }); res.json({ success: true, data: result.rows[0] }); }
async function create(req, res) { const { resourceType, resourceId, requestedDate, startTime, endTime, purpose, researchProject, additionalRequirements } = req.body; if (!resourceType || !resourceId || !requestedDate || !startTime || !endTime || !purpose || !researchProject) return res.status(400).json({ success: false, message: 'Resource, date, times, purpose, and research project are required' }); if (!['facility', 'equipment'].includes(resourceType)) return res.status(400).json({ success: false, message: 'Resource type must be facility or equipment' }); if (startTime >= endTime) return res.status(400).json({ success: false, message: 'End time must be after start time' }); const table = resourceType === 'facility' ? 'facilities' : 'equipment'; const resource = await pool.query(`SELECT id FROM ${table} WHERE id = $1`, [resourceId]); if (!resource.rowCount) return res.status(400).json({ success: false, message: 'Resource not found' }); const result = await pool.query('INSERT INTO resource_requests (user_id, resource_type, resource_id, requested_date, start_time, end_time, purpose, research_project, additional_requirements) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *', [req.user.id, resourceType, resourceId, requestedDate, startTime, endTime, purpose.trim(), researchProject.trim(), additionalRequirements || null]); res.status(201).json({ success: true, data: result.rows[0] }); }
async function updateStatus(req, res) { const { status } = req.body; if (!['Approved', 'Rejected', 'Cancelled'].includes(status)) return res.status(400).json({ success: false, message: 'Status must be Approved, Rejected, or Cancelled' }); const existing = await pool.query('SELECT rr.*, u.department_id FROM resource_requests rr JOIN users u ON u.id = rr.user_id WHERE rr.id = $1', [req.params.id]); if (!existing.rowCount) return res.status(404).json({ success: false, message: 'Request not found' }); const row = existing.rows[0]; if (row.status !== 'Pending') return res.status(400).json({ success: false, message: 'Only Pending requests can change status' }); if (status === 'Cancelled' && row.user_id !== req.user.id) return res.status(403).json({ success: false, message: 'Only the requester can cancel this request' }); if (status !== 'Cancelled' && req.user.role === 'faculty' && row.department_id !== req.user.departmentId) return res.status(403).json({ success: false, message: 'Faculty can only review requests from their department' }); if (status === 'Cancelled' && req.user.role !== 'student') return res.status(403).json({ success: false, message: 'Only students can cancel requests' }); const result = await pool.query('UPDATE resource_requests SET status = $1, updated_at = NOW() WHERE id = $2 RETURNING *', [status, req.params.id]); res.json({ success: true, data: result.rows[0] }); }
async function remove(req, res) { return updateStatus({ ...req, body: { status: 'Cancelled' } }, res); }
module.exports = { list, get, create, updateStatus, remove };
