const pool = require('../config/database');

const configs = {
  facilities: { table: 'facilities', alias: 'f', columns: 'f.id, f.name, f.type, f.description, f.location, f.capacity, f.availability, f.responsible_faculty, f.contact, f.department_id, d.code AS department_code, d.name AS department_name, f.course_code, f.regulation, f.semester, f.batch_size, (SELECT COUNT(*) FROM equipment le WHERE le.lab_id = f.id) AS equipment_count', search: ['f.name', 'f.description', 'f.location', 'f.type', 'f.course_code'] },
  equipment: { table: 'equipment', alias: 'e', columns: 'e.id, e.name, e.category, e.model, e.description, e.quantity, e.location, e.availability, e.responsible_faculty, e.contact, e.department_id, d.code AS department_code, d.name AS department_name, e.lab_id, e.required_quantity, e.available_quantity, e.deficiency, e.unit, e.course_code, e.semester, f.name AS lab_name', search: ['e.name', 'e.description', 'e.location', 'e.category', 'e.model'] },
  expertise: { table: 'expertise', alias: 'x', columns: 'x.id, x.faculty_name, x.designation, x.expertise, x.research_areas, x.email, x.phone, x.department_id, d.code AS department_code, d.name AS department_name', search: ['x.faculty_name', 'x.expertise', 'x.research_areas', 'x.designation'] }
};

function filters(query, config) {
  const values = []; const where = [];
  const add = (expression, value) => { values.push(value); where.push(`${expression} = $${values.length}`); };
  if (query.department) add('d.code', query.department.toUpperCase());
  if (query.availability && config.alias !== 'x') add(`${config.alias}.availability`, query.availability);
  if (query.type && config.alias === 'f') add('f.type', query.type);
  if (query.category && config.alias === 'e') add('e.category', query.category);
  if (query.lab_id && config.alias === 'e') add('e.lab_id', query.lab_id);
  if (query.semester && config.alias === 'f') add('f.semester', query.semester);
  if (query.regulation && config.alias === 'f') add('f.regulation', query.regulation);
  if (query.course_code && config.alias === 'f') add('f.course_code', query.course_code);
  if (query.search) { values.push(`%${query.search}%`); where.push(`(${config.search.map((field) => `CAST(${field} AS TEXT) ILIKE $${values.length}`).join(' OR ')})`); }
  return { values, clause: where.length ? `WHERE ${where.join(' AND ')}` : '' };
}
function departmentId(code) { return pool.query('SELECT id FROM departments WHERE code = $1', [String(code || '').toUpperCase()]); }
function controller(kind) {
  const config = configs[kind];
  return {
    list: async (req, res) => { const { values, clause } = filters(req.query, config); const facilityJoin = kind === 'equipment' ? ' LEFT JOIN facilities f ON f.id = e.lab_id' : ''; const result = await pool.query(`SELECT ${config.columns} FROM ${config.table} ${config.alias} JOIN departments d ON d.id = ${config.alias}.department_id${facilityJoin} ${clause} ORDER BY ${config.alias}.name NULLS LAST`, values); res.json({ success: true, data: result.rows }); },
    get: async (req, res) => { const facilityJoin = kind === 'equipment' ? ' LEFT JOIN facilities f ON f.id = e.lab_id' : ''; const result = await pool.query(`SELECT ${config.columns} FROM ${config.table} ${config.alias} JOIN departments d ON d.id = ${config.alias}.department_id${facilityJoin} WHERE ${config.alias}.id = $1`, [req.params.id]); if (!result.rowCount) return res.status(404).json({ success: false, message: 'Resource not found' }); const data = result.rows[0]; if (kind === 'facilities') { const equipment = await pool.query('SELECT id, name, required_quantity, available_quantity, deficiency, unit, category, model, description FROM equipment WHERE lab_id = $1 ORDER BY id', [req.params.id]); data.equipment = equipment.rows; } res.json({ success: true, data }); },
    create: async (req, res) => { const body = req.body; const name = kind === 'expertise' ? body.facultyName : body.name; if (!name || !body.departmentCode) return res.status(400).json({ success: false, message: 'Name and departmentCode are required' }); const department = await departmentId(body.departmentCode); if (!department.rowCount) return res.status(400).json({ success: false, message: 'Department must be IT, CSE, ECE, EEE, or MECH' }); const definitions = kind === 'facilities' ? [['name','name'],['type','type'],['description','description'],['location','location'],['capacity','capacity'],['availability','availability'],['responsibleFaculty','responsible_faculty'],['contact','contact'],['courseCode','course_code'],['regulation','regulation'],['semester','semester'],['batchSize','batch_size']] : kind === 'equipment' ? [['name','name'],['category','category'],['model','model'],['description','description'],['quantity','quantity'],['location','location'],['availability','availability'],['responsibleFaculty','responsible_faculty'],['contact','contact'],['labId','lab_id'],['requiredQuantity','required_quantity'],['availableQuantity','available_quantity'],['unit','unit'],['courseCode','course_code'],['semester','semester']] : [['facultyName','faculty_name'],['designation','designation'],['expertise','expertise'],['researchAreas','research_areas'],['email','email'],['phone','phone']]; const columns = ['department_id']; const values = [department.rows[0].id]; const placeholders = ['$1']; definitions.forEach(([key, column]) => { if (body[key] !== undefined) { columns.push(column); values.push(body[key]); placeholders.push(`$${values.length}`); } }); const result = await pool.query(`INSERT INTO ${config.table} (${columns.join(', ')}) VALUES (${placeholders.join(', ')}) RETURNING *`, values); res.status(201).json({ success: true, data: result.rows[0] }); },
    update: async (req, res) => { const body = req.body; const mapping = kind === 'expertise' ? { facultyName:'faculty_name', designation:'designation', expertise:'expertise', researchAreas:'research_areas', email:'email', phone:'phone' } : kind === 'facilities' ? { name:'name', type:'type', description:'description', location:'location', capacity:'capacity', availability:'availability', responsibleFaculty:'responsible_faculty', contact:'contact', courseCode:'course_code', regulation:'regulation', semester:'semester', batchSize:'batch_size' } : { name:'name', category:'category', model:'model', description:'description', quantity:'quantity', location:'location', availability:'availability', responsibleFaculty:'responsible_faculty', contact:'contact', labId:'lab_id', requiredQuantity:'required_quantity', availableQuantity:'available_quantity', unit:'unit', courseCode:'course_code', semester:'semester' }; const values = []; const updates = []; for (const [key, column] of Object.entries(mapping)) if (body[key] !== undefined) { values.push(body[key]); updates.push(`${column} = $${values.length}`); } if (body.departmentCode) { const department = await departmentId(body.departmentCode); if (!department.rowCount) return res.status(400).json({ success: false, message: 'Invalid department' }); values.push(department.rows[0].id); updates.push(`department_id = $${values.length}`); } if (!updates.length) return res.status(400).json({ success: false, message: 'No fields to update' }); values.push(req.params.id); const result = await pool.query(`UPDATE ${config.table} SET ${updates.join(', ')}, updated_at = NOW() WHERE id = $${values.length} RETURNING *`, values); if (!result.rowCount) return res.status(404).json({ success: false, message: 'Resource not found' }); res.json({ success: true, data: result.rows[0] }); },
    remove: async (req, res) => { const result = await pool.query(`DELETE FROM ${config.table} WHERE id = $1 RETURNING id`, [req.params.id]); if (!result.rowCount) return res.status(404).json({ success: false, message: 'Resource not found' }); res.json({ success: true, data: { id: result.rows[0].id } }); }
  };
}
module.exports = { controller };
